### ISSUE TITLE
Update python proxy to work with html2canvas 0.5.X?

### ISSUE THREAD

**Issue by pavitrakumar78** [brcontainer/html2canvas-python-proxy#3]
Hi,

I tried your python proxy for html2cavas 0.5.X, but it is not working - I saw that you have updated the PHP proxy for html2canvas - can you help me with getting a python proxy working with the latest html2canvas?
(I am using Flask backend for my project).    
I have written about the errors I get running this python proxy with html2cavas latest version [here](https://github.com/niklasvh/html2canvas/issues/1229).

**Comment by brcontainer** [comment]
@pavitrakumar78 I will try, thanks.

**Comment by pavitrakumar78** [comment]
Thank you! Looking forward to your updates!

**Comment by brcontainer** [comment]
@pavitrakumar78 work fine for me using https://github.com/brcontainer/html2canvas-python-proxy/tree/master/flask.

- Are you using Python2.7 or 3.1, 3.2, 3.3, 3.4, 3.5 or 3.6?
- Have you made any adjustments to the html2canvasproxy.py?
- do you have a firewall rule?

**Comment by pavitrakumar78** [comment]
@brcontainer 

- I am using python 2.7
- No adjustments to html2canvasproxy.py or to html2canvas.js (v0.5.X)
- No firewall rule

How come it is not working for me?... I thought the internals of how external images were handled were changed with thml2canvas.js 0.5.X version. The code in your repo works perfectly for html2canas 0.4.1 version.

**Comment by brcontainer** [comment]
@pavitrakumar78 thanks by info, i will try in Firefox and Chrome 👽

**Comment by pavitrakumar78** [comment]
@brcontainer  hey! any updates on this?

**Comment by brcontainer** [comment]
@pavitrakumar78 I get error, new "proxy engine" don't use callback, I will improve the php script. Thanks!

**Comment by brcontainer** [comment]
@pavitrakumar78 fixed https://github.com/brcontainer/html2canvas-python-proxy/commit/81dfa3dda4f030bae5e36500ddbb98d0da3534da, download this: https://github.com/brcontainer/html2canvas-python-proxy/blob/master/html2canvasproxy.py

**Comment by pavitrakumar78** [comment]
@brcontainer  hey! thanks for the fixes, everything works fine now! 👍
