### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by QA-Rahul** [brcontainer/html2canvas-python-proxy#5]
![image](https://user-images.githubusercontent.com/18675695/74312124-0e16d800-4d97-11ea-842a-f013ec96c667.png)

Getting error when import. Does it need any installation?

**Comment by brcontainer** [comment]
Did you move the "html2canvasproxy.py" file to the folder where your main script is located?

ps: I intend to publish in PyPI (https://pypi.org/) soon. Probably this weekend.

**Comment by QA-Rahul** [comment]
Hey I did not move that file. Do I need to add only that file into my project root folder? @brcontainer

**Comment by brcontainer** [comment]
> Hey I did not move that file. Do I need to add only that file into my project root

that's right, new to the folder where your main script that will use the proxy is located.
